site:
  title: Stampede Studios
  url: https://stampedestudios.github.io
  start_page: cow-defenders:ROOT:index.adoc
content:
  sources:
  - url: https://ANTORA_TOKEN@github.com/StampedeStudios/cow-defenders-documentation.git
    branches: main
    version: 0.1.0
    tags:
    - tower-defense
    - top-down
    - sci-fi
    - pixel-art

ui:
  bundle:
    url: ./assets/ui-bundle.zip
    snapshot: true